@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Component diagram van TripTop voor het TripTop systeem

Person(reiziger, "Reiziger", "Stelt de reis samen, boekt, annuleert, past aan en betaalt")
Person(ondersteuner, "Reis Agent", "Tweedelijns support; helpt reiziger bij vragen")

Container_Boundary(triptop, "Boeking Systeem") {
    Container(controller, "BoekingController", "Java, Spring Boot", "Verwerkt boekingen aanvragen")
    Container(service, "BoekingService", "Java, Spring Boot", "Bevat businesslogica voor verwerken boeking")
    Container(facade, "FacadeService", "Java, Spring Boot", "Verwerkt boeking aanvragen met intern systeem en externe api")
    Container(boeking_repository, "BoekingRepository", "Java, Spring Boot", "Slaat boekingen op in de database")
    Container(booking_com_adapter, "BookingComAdapter", "Java, Spring Boot", "Legt verbinding met Booking.com API")
    Container(triptop_service, "TripTopService", "Java, Spring Boot", "Bevat businesslogica voor intern boekingssysteem")
}

 Container(frontend, "Frontend", "React, JavaScript", "Stelt gebruikers in staat om reizen te plannen, boeken, beheren en betalen")
 ContainerDb(database, "Database", "MSSQL", "Opslag van boekingen")

System_Ext(booking, "Booking API ", "Geeft toegang tot een breed scala aan accommodaties,boekingsmogelijkheden en een netwerk van autoverhuurlocaties en -diensten")


' Relaties gebruiker naar containers
Rel(reiziger, frontend, "Gebruikt via webbrowser")
Rel(ondersteuner, frontend, "Ondersteunt reizigers via webinterface")

' Relaties tussen containers binnen TripTop
Rel(frontend, controller, "Stuurt verzoeken naar backend via REST API (JSON/HTTPS)")
Rel(controller, service, "Geeft verzoeken door aan de service", "REST")
Rel(service, facade, "Geeft verzoeken door aan de facade", "REST")
Rel(service, boeking_repository, "Geeft opgehaalde data mee aan de repository", "REST")
Rel(boeking_repository, database, "Slaat boekingen op", "JSON/HTTPS")
Rel(facade, booking_com_adapter, "Vraagt overnachtingsmogelijkheden op", "REST")
Rel(facade, triptop_service, "Haalt overnachtingsmogelijkheden intern op.", "REST")
' Relaties backend naar externe systemen
Rel_U(booking_com_adapter, booking, "Haalt overnachtingsmogelijkheden op via REST API", "JSON/HTTPS")
@enduml
