@startuml
skinparam rankdir TB
title Login Component Class Diagram

class LoginController <<Controller>> {
    - LoginService loginService
    --
    + AuthToken authenticate(Reiziger reiziger) throws AuthenticationException
}

class LoginService <<Service>> {
    + AuthToken authenticate(Reiziger reiziger) throws AuthenticationException
    + handleFallbackScenario() ' optioneel
    - LoginPort loginPort
    - LoginRepo loginRepo
}

class AuthenticationException <<Exception>>

interface LoginPort <<Port>> {
    + AuthToken authenticateExternal(Reiziger reiziger) throws AuthenticationException
}

class WireMockAdapterV1 <<Adapter>> {
    + AuthToken authenticateExternal(Reiziger reiziger) throws AuthenticationException
}

class WireMockAdapterV2 <<Adapter>> {
    + AuthToken authenticateExternal(Reiziger reiziger) throws AuthenticationException
}

interface LoginRepo <<Port>> {
    + Reiziger authenticate(Reiziger reiziger) throws AuthenticationException
}

class LoginRepoImpl <<Repository>> {
    + Reiziger authenticate(Reiziger reiziger) throws AuthenticationException
}

class Reiziger <<Entity>> {
    - String username
    - String password
}

LoginController --> LoginService : uses
LoginService --> AuthenticationException : «throws»
LoginService --> LoginPort : uses
LoginPort <|.. WireMockAdapterV1 : «implements»
LoginPort <|.. WireMockAdapterV2 : «implements»
LoginService --> LoginRepo : uses
LoginRepo <|.. LoginRepoImpl : «implements»

@enduml
