@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
title Dynamic Diagram

Person(reiziger, "Reiziger", "Gebruiker die inlogt")
Container(frontend, "Frontend", "React, JavaScript", "Stuurt inlogverzoek")

System_Boundary(backendSystem, "Backend (Java, Spring Boot)") {

  Component(loginController, "Login Controller", "Spring MVC", "Verwerkt inlogverzoeken")
  Component(loginService, "Login Service", "Spring Service", "Behandelt authenticatie en inloglogica")
  Component(loginPort, "AuthAdapter", "Interface", "Definieert een stabiel contract voor externe authenticatie")
  Component(userRepository, "User Repository", "Spring Data JPA", "Beheert opslag van gebruikersgegevens")
  Component(wireMockAdapterV2, "WireMock Adapter v2", "Adapter Pattern", "Implementeert AuthAdapter voor de WireMock API (v2)")


}
Container(database, "Database", "MSSQL", "Slaat gebruikers- en tokengegevens op")

Container_Ext(identityProvider, "WireMock API (v2)", "Simuleert centrale identiteitsverificatie en SSO")

Rel_D(reiziger, frontend, "1 Voert gebruikersnaam & wachtwoord in", "HTTPS")
Rel_D(frontend, loginController, "2 Stuurt inlogverzoek", "HTTPS")
Rel_D(loginController, loginService, "3 Verwerkt inlogverzoek", "JSON/HTTP")
Rel_D(loginService, loginPort, "4 Stuurt authenticatieverzoek", "REST/JSON")
Rel_D(loginPort, wireMockAdapterV2, "5 Implementeert (v2)", "REST/JSON")

Rel_D(wireMockAdapterV2, identityProvider, "6 Verifieert inloggegevens", "REST/JSON")

Rel_D(identityProvider, wireMockAdapterV2, "7 Retourneert LoginResponse", "REST/JSON")
Rel_D(loginPort, loginService, "8 Retourneert ", "REST/JSON")

Rel_D(loginService, userRepository, "9 Slaat LoginResponse of gebruikersdata op", "JDBC/SQL")
Rel_D(userRepository, database, "10 Voert CRUD-operatie uit", "JDBC/SQL")
Rel_D(database, userRepository, "11 Bevestigt operatie", "JDBC/SQL")
Rel_D(userRepository, loginService, "12 Resultaat data/opslaan", "JDBC/SQL")

Rel_D(loginService, loginController, "13 Retourneert LoginResponse", "JSON/HTTP")
Rel_D(loginController, frontend, "14 Retourneert LoginResponse", "HTTPS")
Rel_D(frontend, reiziger, "15 Reiziger is ingelogd", "HTTPS")
@enduml
