@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
title Dynamisch Sequence Diagram – TripTop Backend

actor "Reiziger" as User
participant "Frontend" as FE
participant "Login Controller" as LC
participant "Login Service" as LS
participant "Auth Adapter" as AA
participant "UserRepository" as UR
participant "Database" as DB
participant "WireMock API (v1)" as WMV1
participant "WireMock API (v2)" as WMV2
participant "user:\n User " as user
User -> FE: Voert inloggegevens in\n(AuthLoginRequest DTO)
FE -> LC: POST /auth/login\n(AuthLoginRequest)
LC -> LS: login(loginRequest)
LS -> AA: login(username, password)
alt Gebruik WireMock API v1
  AA -> WMV1: POST /login\n(JSON body: username, password)
  WMV1 --> AA: JSON response\n{ "token": "abc123def456" }\n
else Gebruik WireMock API v2
  AA -> WMV2: POST /login\n(JSON body: username, password)
  WMV2 --> AA: Response header\n{ token: "v2_abcdefghijklmnop" }\n
end
AA --> LS: token
LS -> UR:user = findByUsername(username)
LS -> user: setToken(token)
LS -> UR: save(user)
UR --> LS: Opslaan bevestigd
LS --> LC: Retourneer LoginResponse DTO\n{ token }
LC --> FE: HTTP 200\n(LoginResponse DTO)
FE --> User: Reiziger is ingelogd

User -> FE: Start check-access actie\n(CheckRequest DTO)
FE -> LC: POST /auth/check\n(CheckRequest)
LC -> LS: check(token, checkRequest)
LS -> AA: check(token, username, application)
alt Gebruik WireMock API v1
  AA -> WMV1: POST /checkAppAccess?token=xxx\n(JSON body: username, application)
  WMV1 --> AA: JSON response\n{ "access": "allowed", "role": "klant" }
else Gebruik WireMock API v2
  AA -> WMV2: POST /checkAppAccess\n(Token in header, JSON body: username, application)
  WMV2 --> AA: XML response\n<response><access>allowed</access><role>klant</role></response>
  note right of AA: "De V2 adapter verwerkt de XML response\nen zet deze om naar een CheckResponse DTO"
end
AA --> LS: Retourneer CheckResponse DTO
LS --> LC: Retourneer CheckResponse DTO
LC --> FE: HTTP 200\n(CheckResponse DTO)
FE --> User: Toegang: allowed, Rol: klant


@enduml
