@startuml

package "Controller Layer" {
    class PaymentController {
        + processPayment(paymentRequest: PaymentRequest): ResponseEntity
    }
}

package "Service Layer" {
    class PaymentService {
        + handlePayment(paymentRequest: PaymentRequest): PaymentResponse
    }

}

package "Repository Layer" {
    interface PaymentRepository {
        + save(payment: Payment): void
    }
}

package "Model Layer" {
    class Payment {
        Long id
        Double amount
        String status
    }
}

package "Adapter Layer" {
    interface PaymentGateway {
        + processPayment(amount: Double): PaymentResponse
    }
    class StripeAdapter implements PaymentGateway {
        + processPayment(amount: Double): PaymentResponse
    }


}

PaymentService --> PaymentGateway
StripeAdapter ..|> PaymentGateway

PaymentController --> PaymentService


PaymentService --> PaymentRepository

TripRepository --> Trip
PaymentRepository --> Payment

@enduml