@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Container diagram van TripTop voor het TripTop systeem

Person(reiziger, "Reiziger", "Stelt de reis samen, boekt, annuleert, past aan en betaalt")

System_Boundary(triptop, "TripTop") {
    Container(frontend, "Frontend", "React, JavaScript", "Stelt gebruikers in staat om reizen te plannen, boeken, beheren en betalen")
    Container(backend, "Backend", "Java, Spring Boot", "Verwerkt boekingen, beheert bouwstenen en integreert externe services")
    Container(database, "Database", "MSSQL", "Slaat reizen, bouwstenen en gebruikersgegevens op")
}

System_Ext(identity_provider, "WireMock API", "Simuleert centrale identiteitsverificatie en Single Sign-On voor testdoeleinden")
System_Ext(payment_provider, "Stripe API", "Faciliteert veilige online betalingstransacties")
System_Ext(booking, "Booking API ", "Geeft toegang tot een breed scala aan accommodaties,boekingsmogelijkheden en een netwerk van autoverhuurlocaties en -diensten")
System_Ext(vervoer_services, "NS API", "Levert real-time informatie over treinreizen ")
System_Ext(routeplanner_service, "Maps API", "Biedt geavanceerde routeplanningsfunctionaliteit en alternatieve reisopties")
System_Ext(activiteiten_services, "Tripadvisor API", "Verstrekt gedetailleerde informatie over lokale attracties, excursies en bezienswaardigheden")
System_Ext(eten_services, "UberEats API", "Biedt een overzicht van restaurants, cafés en andere ervaringen op de bestemming")

' Relaties gebruiker naar containers
Rel(reiziger, frontend, "Gebruikt via webbrowser")

' Relaties tussen containers binnen TripTop
Rel(frontend, backend, "Stuurt verzoeken naar backend via REST API (JSON/HTTPS)")
Rel_L(backend, database, "Leest/schrijft gegevens naar database via JDBC","JDBC/SQL")

' Relaties backend naar externe systemen
Rel(backend, identity_provider, "Authenticeert gebruikers  (HTTPS)")
Rel(backend, payment_provider, "Verwerkt betalingen via REST API (JSON/HTTPS)")

Rel(backend, booking, "Haalt overnachtingsmogelijkheden op en boekt via REST API (JSON/HTTPS)")
Rel(backend, vervoer_services, "Haalt vervoersmogelijkheden op en boekt via REST API (JSON/HTTPS)")
Rel(backend, routeplanner_service, "Haalt routes op via REST API (JSON/HTTPS)")
Rel(backend, activiteiten_services, "Haalt activiteiten/excursies op en boekt via REST API (JSON/HTTPS)")
Rel(backend, eten_services, "Haalt eet- en drinkmogelijkheden op via REST API (JSON/HTTPS)")
@enduml
