@startuml
title Class Diagram – Boeking Hoe kunnen verschillende boekingsservices (zoals Booking.com en eigen beheer in Triptop) worden geïntegreerd?

class Boeking {
    -Int boekingId
    -Int reizigerId
    -Date boekingsDatum
    -Date vertrekDatum
    -Date aankomstDatum
    -String vertrekLocatie
    -String aankomstLocatie
    -Double prijs
}
class BoekingController {
    - BoekingService boekingService
    + haalOvernachtingenOp(): List<Boeking>
    + slaBoekingenOp(): List<Boeking>
}


class BoekingRepository {
    + slaBoekingenOp()
}


class BoekingOverzichtService {
    - BoekingRepository boekingRepository
    - BookingComAdapter bookingComAdapter
    - InternBoekingSysteem tripTopService
    - haalOvernachtingenOp(): List<Boeking>
    - slaBoekingenOp(): List<Boeking>
    - haalExterneOvernachtingenOp(): List<Boeking>
    - haalInterneOvernachtingenOp(): List<Boeking>
}

class BookingComAdapter {
    - haalOvernachtingenOp()
}

class InternBoekingSysteem {
    - haalOvernachtingenOp()
}

interface BoekingInterface {
    # haalExterneBoekingenOp(): List<Boeking>
    # haalInterneBoekingenOp(): List<Boeking>
}

BoekingController --> BoekingOverzichtService: "gebruikt"
BoekingController --> Boeking: "gebruikt"
BoekingOverzichtService --> BoekingRepository: "gebruikt"
BoekingOverzichtService --> BoekingInterface: "implementeert"
BoekingOverzichtService  --> BookingComAdapter : "gebruikt"
BoekingOverzichtService --> InternBoekingSysteem : "gebruikt"


@enduml