@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml

title Component diagram van TripTop voor het TripTop systeem

Person(reiziger, "Reiziger", "Stelt de reis samen, boekt, annuleert, past aan en betaalt")
Person(ondersteuner, "Reis Agent", "Tweedelijns support; helpt reiziger bij vragen")

System_Boundary(triptop, "Boeking Systeem") {
    Component(controller, "BoekingController", "Java, Spring Boot", "Verwerkt boekingen aanvragen")
    Component(boeking_overzicht_service, BoekingOverzichtService, "Java, Spring Boot", "Verwerkt boeking aanvragen met intern systeem en externe api")
    Component(boeking_repository, "BoekingRepository", "Java, Spring Boot", "Slaat boekingen op in de database")
    Component(booking_com_adapter, "BookingComAdapter", "Java, Spring Boot", "Legt verbinding met Booking.com API")
    Component(intern_boeking_systeem, "Intern boekingssysteem", "Java, Spring Boot", "Bevat businesslogica voor intern boekingssysteem")
}

 Container(frontend, "Frontend", "React, JavaScript", "Stelt gebruikers in staat om reizen te plannen, boeken, beheren en betalen")
 ContainerDb(database, "Database", "MSSQL", "Opslag van boekingen")

System_Ext(booking, "Booking API ", "Geeft toegang tot een breed scala aan accommodaties,boekingsmogelijkheden en een netwerk van autoverhuurlocaties en -diensten")


' Relaties gebruiker naar containers
Rel(reiziger, frontend, "Gebruikt via webbrowser")
Rel(ondersteuner, frontend, "Ondersteunt reizigers via webinterface")

' Relaties tussen containers binnen TripTop
Rel(frontend, controller, "Stuurt verzoeken naar backend via REST API (JSON/HTTPS)")
Rel(controller, boeking_overzicht_service, "Geeft verzoeken door aan de service", "REST")
Rel(boeking_overzicht_service, booking_com_adapter, "Vraagt overnachtingsmogelijkheden op", "REST")
' Relaties backend naar externe systemen
Rel_U(booking_com_adapter, booking, "Vraagt overnachtingsmogelijkheden op via REST API", "JSON/HTTPS")
Rel_U(booking, booking_com_adapter, "Geeft overnachtingsmogelijkheden terug via REST API", "JSON/HTTPS")
Rel_U(booking_com_adapter, boeking_overzicht_service, "Geeft overnachtingsmogelijkheden door aan de service", "JSON/HTTPS")
Rel(boeking_overzicht_service, intern_boeking_systeem, "Haalt overnachtingsmogelijkheden intern op.", "REST")
Rel(intern_boeking_systeem, database, "Haalt overnachtingsmogelijkheden op.", "REST")
Rel_U(intern_boeking_systeem, boeking_overzicht_service, "Geeft overnachtingsmogelijkheden terug aan de service", "REST")
Rel(boeking_overzicht_service, boeking_repository, "Geeft boeking mee aan de repository", "REST")
Rel(boeking_repository, database, "Slaat boekingen op", "JSON/HTTPS")
@enduml
